from __future__ import annotations

from collections import Counter
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from ai_provider_watch.core.io import read_json


@dataclass(frozen=True)
class CandidateFile:
    path: Path
    payload: dict[str, Any]


def read_candidate_files(candidate_dir: Path) -> list[CandidateFile]:
    if not candidate_dir.exists():
        return []
    candidates: list[CandidateFile] = []
    for path in sorted(candidate_dir.rglob("*.json")):
        payload = read_json(path)
        candidates.append(
            CandidateFile(
                path=path,
                payload=payload if isinstance(payload, dict) else {"id": "<invalid>"},
            )
        )
    return candidates


def _observations(bundle: Any) -> list[dict[str, Any]]:
    if not isinstance(bundle, dict):
        return []
    observations = bundle.get("observations", [])
    return [item for item in observations if isinstance(item, dict)] if isinstance(observations, list) else []


def _changed_source_keys(bundle: Any, observations: list[dict[str, Any]]) -> list[str]:
    if isinstance(bundle, dict):
        changed_source_keys = bundle.get("changed_source_keys", [])
        if isinstance(changed_source_keys, list):
            return sorted({item for item in changed_source_keys if isinstance(item, str)})
    return sorted(
        {
            str(observation.get("source_key"))
            for observation in observations
            if observation.get("changed") is True and observation.get("source_key")
        }
    )


def _candidate_path(path: Path, root: Path) -> str:
    try:
        return path.relative_to(root).as_posix()
    except ValueError:
        return path.as_posix()


def _candidate_rows(candidate_files: list[CandidateFile], root: Path) -> list[str]:
    rows: list[str] = []
    for candidate_file in candidate_files:
        candidate = candidate_file.payload
        source_keys = candidate.get("source_keys", [])
        provider_refs = candidate.get("provider_refs", [])
        evidence_refs = candidate.get("evidence_refs", [])
        rows.append(
            "| "
            + " | ".join(
                [
                    _candidate_path(candidate_file.path, root),
                    str(candidate.get("id", "<missing>")),
                    str(candidate.get("candidate_kind", "<missing>")),
                    ", ".join(source_keys) if isinstance(source_keys, list) else "<invalid>",
                    ", ".join(provider_refs) if isinstance(provider_refs, list) else "<invalid>",
                    str(len(evidence_refs) if isinstance(evidence_refs, list) else 0),
                ]
            )
            + " |"
        )
    return rows


def build_review_pr_body(
    observation_bundle: Any,
    candidate_files: list[CandidateFile],
    *,
    root: Path,
    validation_output: str = "",
) -> str:
    observations = _observations(observation_bundle)
    changed_source_keys = _changed_source_keys(observation_bundle, observations)
    candidate_count_by_source: Counter[str] = Counter()
    candidate_count_by_kind: Counter[str] = Counter()
    for candidate_file in candidate_files:
        candidate = candidate_file.payload
        for source_key in candidate.get("source_keys", []):
            if isinstance(source_key, str):
                candidate_count_by_source[source_key] += 1
        candidate_kind = candidate.get("candidate_kind")
        if isinstance(candidate_kind, str):
            candidate_count_by_kind[candidate_kind] += 1

    lines = [
        "# Candidate Review",
        "",
        "This draft PR was generated by the deterministic official-source refresh workflow.",
        "Provider source text is untrusted data; this body intentionally omits raw source text and candidate claim text.",
        "",
        "## Summary",
        "",
        f"- Observation count: {len(observations)}",
        f"- Changed source keys: {len(changed_source_keys)}",
        f"- Candidate files: {len(candidate_files)}",
        f"- Candidate kinds: {_render_counter(candidate_count_by_kind)}",
        "",
        "## Changed Sources",
        "",
    ]
    if changed_source_keys:
        lines.extend([f"- `{source_key}`" for source_key in changed_source_keys])
    else:
        lines.append("- None reported.")

    lines.extend(
        [
            "",
            "## Observation Summary",
            "",
            "| Source | Changed | HTTP | Candidate claims | Errors | Fingerprint |",
            "| --- | --- | ---: | ---: | ---: | --- |",
        ]
    )
    for observation in observations:
        source_key = str(observation.get("source_key", "<missing>"))
        claims = observation.get("candidate_claims", [])
        errors = observation.get("errors", [])
        fingerprint = str(observation.get("fingerprint", ""))
        lines.append(
            "| "
            + " | ".join(
                [
                    f"`{source_key}`",
                    "yes" if observation.get("changed") is True else "no",
                    str(observation.get("http_status", "<missing>")),
                    str(len(claims) if isinstance(claims, list) else 0),
                    str(len(errors) if isinstance(errors, list) else 0),
                    f"`{fingerprint[:12]}`" if fingerprint else "`<missing>`",
                ]
            )
            + " |"
        )

    lines.extend(
        [
            "",
            "## Candidate Files",
            "",
        ]
    )
    if candidate_files:
        lines.extend(
            [
                "| Path | ID | Kind | Sources | Providers | Evidence refs |",
                "| --- | --- | --- | --- | --- | ---: |",
                *_candidate_rows(candidate_files, root),
            ]
        )
    else:
        lines.append("No candidate files were generated in this run.")

    lines.extend(
        [
            "",
            "## Validation",
            "",
            "```text",
            validation_output.strip() or "Validation output was not supplied.",
            "```",
            "",
            "## Reviewer Checklist",
            "",
            "- [ ] Confirm source fingerprint changes are expected and official.",
            "- [ ] Review each candidate JSON file against its official evidence URL before promotion.",
            "- [ ] Keep provider prose, raw HTML, screenshots, and social/community text out of committed event data.",
            "- [ ] Promote only reviewed factual changes to `data/events/`; candidates are not published provider events.",
            "- [ ] Do not merge if candidate evidence points outside allowed domains or validation output is stale.",
        ]
    )
    return "\n".join(lines) + "\n"


def _render_counter(counter: Counter[str]) -> str:
    if not counter:
        return "none"
    return ", ".join(f"{key}={counter[key]}" for key in sorted(counter))
